// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course.Domain.Models;

public partial class CourseComment
{
    public Guid CommentId { get; set; }

    public Guid CourseId { get; set; }

    public Guid UserId { get; set; }

    public string Content { get; set; }

    public Guid? ParentCommentId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsActive { get; set; }

    public virtual Course Course { get; set; }

    public virtual ICollection<CourseComment> InverseParentComment { get; set; } = new List<CourseComment>();

    public virtual CourseComment ParentComment { get; set; }
}