// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course.Domain.Models;

public partial class CourseRecommendation
{
    public Guid RecommendationId { get; set; }

    public Guid UserId { get; set; }

    public Guid CourseId { get; set; }

    public string AlgoVersion { get; set; }

    public decimal Score { get; set; }

    public string ReasonJson { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Course Course { get; set; }
}