// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course.Domain.Models;

public partial class CourseRating
{
    public Guid RatingId { get; set; }

    public Guid CourseId { get; set; }

    public Guid UserId { get; set; }

    public short Rating { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Course Course { get; set; }
}