// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course.Domain.Models;

public partial class Course
{
    public Guid CourseId { get; set; }

    public Guid TeacherId { get; set; }

    public Guid SubjectId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int? DurationMinutes { get; set; }

    public short? Level { get; set; }

    public decimal Price { get; set; }

    public decimal? DealPrice { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<CourseComment> CourseComments { get; set; } = new List<CourseComment>();

    public virtual ICollection<CourseRating> CourseRatings { get; set; } = new List<CourseRating>();

    public virtual ICollection<CourseRecommendation> CourseRecommendations { get; set; } = new List<CourseRecommendation>();

    public virtual ICollection<CourseTag> CourseTags { get; set; } = new List<CourseTag>();

    public virtual ICollection<Module> Modules { get; set; } = new List<Module>();

    public virtual Subject Subject { get; set; }
}