// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course.Domain.Models;

public partial class Lesson
{
    public Guid LessonId { get; set; }

    public Guid ModuleId { get; set; }

    public string Title { get; set; }

    public string VideoUrl { get; set; }

    public int? VideoDurationSec { get; set; }

    public int PositionIndex { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsActive { get; set; }

    public virtual Module Module { get; set; }

    public virtual ICollection<Note> Notes { get; set; } = new List<Note>();

    public virtual ICollection<UserLessonProgress> UserLessonProgresses { get; set; } = new List<UserLessonProgress>();
}