// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course.Domain.Models;

public partial class Major
{
    public Guid MajorId { get; set; }

    public string MajorCode { get; set; }

    public string MajorName { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Syllabus> Syllabi { get; set; } = new List<Syllabus>();
}