// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course.Domain.Models;

public partial class Note
{
    public Guid NoteId { get; set; }

    public Guid UserId { get; set; }

    public Guid LessonId { get; set; }

    public int TimeSeconds { get; set; }

    public string Content { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual Lesson Lesson { get; set; }
}