// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course.Domain.Models;

public partial class Semester
{
    public Guid SemesterId { get; set; }

    public string SemesterCode { get; set; }

    public string SemesterName { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<SyllabusSemester> SyllabusSemesters { get; set; } = new List<SyllabusSemester>();

    public virtual ICollection<SyllabusSubject> SyllabusSubjects { get; set; } = new List<SyllabusSubject>();
}