// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course.Domain.Models;

public partial class Subject
{
    public Guid SubjectId { get; set; }

    public string SubjectCode { get; set; }

    public string SubjectName { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();

    public virtual ICollection<SyllabusSubject> SyllabusSubjects { get; set; } = new List<SyllabusSubject>();

    public virtual ICollection<Subject> PrereqSubjects { get; set; } = new List<Subject>();

    public virtual ICollection<Subject> Subjects { get; set; } = new List<Subject>();
}