// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course.Domain.Models;

public partial class SyllabusSemester
{
    public Guid SyllabusId { get; set; }

    public Guid SemesterId { get; set; }

    public int PositionIndex { get; set; }

    public virtual Semester Semester { get; set; }

    public virtual Syllabus Syllabus { get; set; }
}