// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course.Domain.Models;

public partial class Syllabus
{
    public Guid SyllabusId { get; set; }

    public Guid MajorId { get; set; }

    public string VersionLabel { get; set; }

    public DateOnly EffectiveFrom { get; set; }

    public DateOnly? EffectiveTo { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsActive { get; set; }

    public virtual Major Major { get; set; }

    public virtual ICollection<SyllabusSemester> SyllabusSemesters { get; set; } = new List<SyllabusSemester>();

    public virtual ICollection<SyllabusSubject> SyllabusSubjects { get; set; } = new List<SyllabusSubject>();
}