// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course.Domain.Models;

public partial class Tag
{
    public long TagId { get; set; }

    public string TagName { get; set; }

    public virtual ICollection<CourseTag> CourseTags { get; set; } = new List<CourseTag>();
}