// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course.Domain.Models;

public partial class UserLessonProgress
{
    public Guid UserLessonProgressId { get; set; }

    public Guid UserId { get; set; }

    public Guid LessonId { get; set; }

    public short Status { get; set; }

    public DateTime? CompletedAt { get; set; }

    public int DurationWatchedSec { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Lesson Lesson { get; set; }
}